development:
  secret_key_base: 69619d9a75b78f2e1c87ec5e07541b42f23efeb6a54e97da3723de06fe74af29d5718adff77d2b04b2805d3a1e143fa61baacfbf4ca2c6fcc608cff8d5a28e8d
  aws_access_key_id: AKIAJFDT3NDWAVGRFRYQ

  aws_secret_access_key: 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


test:
  secret_key_base: ~~~~~~~~

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: AKIAJFDT3NDWAVGRFRYQ

  aws_secret_access_key: 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
